# ---
# - name: Pull Docker Image from Docker Hub
#   hosts: localhost
#   remote_user: siddharth-dhurandhar
#   become: false
#   tasks:

#     # - name: Install Python Docker SDK
#     #   pip:
#     #     name: docker
#     #     executable: pip3

#     - name: Pull Docker Image
#       docker_image:
#         name: "siddharth610/calculator"
#         source: pull
#       register: docker_pull_result

#     - name: Display Docker Pull Result
#       debug:
#         var: docker_pull_result
        
#     - name: Start Docker service
#       service:
#         name: docker
#         state: started

#     - name: Running container
#       shell: docker run -it -d --name calculator siddharth610/calculator /bin/bash

# chatgpt wala playbook from here:-
---
- name: Deploy Docker Container
  hosts: localhost
  remote_user: jenkins
  become: false
  tasks:

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
      become: true  # Requires root access

    - name: Set Docker API environment
      shell: export DOCKER_HOST=unix:///var/run/docker.sock

    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "siddharth610/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Remove existing container if running
      shell: docker rm -f calculator || true
      ignore_errors: true  # Ignore if the container does not exist

    - name: Run the Calculator container
      shell: docker run -it -d --name calculator siddharth610/calculator /bin/bash
